#Конфигурация монтиторинга наших систем

#Порог исп диска в процентах
DISK_THRESHOLD=80

#Порог исп RAM
RAM_THRESHOLD=80

#Основной список серверов для провервки(возможно в будушем добавлю еще)

SERVICES="nginx docker ssh"

#Путь к лог-файлу(в будущем возможно будет как уведомление в телеграм)
LOG_FILE="/var/log/monitor.log"
